spring:
  application:
    name: certification-repository-prod

  datasource:
    url: jdbc:postgresql://localhost:5432/certification_db
    driver-class-name: org.postgresql.Driver
    username: certification_user
    password: certification_pass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  logging:
    level:
      org.springframework.security: WARN
      org.springframework.security.oauth2: WARN
      org.hibernate.SQL: WARN 