spring:
  application:
    name: certification-repository

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  datasource:
    url: jdbc:h2:file:./data/dev-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.security.oauth2: DEBUG