spring:
  application:
    name: certification-repository

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  datasource:
    url: jdbc:h2:file:./data/dev-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

  logging:
    level:
      org.springframework.security: DEBUG